// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Workaround for cross-tab deadlock in gotrue-js. Uses lock if available,
    // but fails open immediately to allow queries instead of freezing the app.
    lock: async (name, acquireTimeout, fn) => {
      if (typeof navigator !== 'undefined' && navigator.locks) {
        return await navigator.locks.request(name, { mode: 'exclusive', ifAvailable: true }, async (lock) => {
          if (lock) {
            return await fn();
          } else {
            // Lock is held by another tab, but waiting would deadlock this tab.
            return await fn();
          }
        });
      }
      return await fn();
    },
  }
});